--- #YAML:1.0
name:               Catalyst-Plugin-Authentication-Credential-HTTP-Proxy
version:            0.02
abstract:           ~
author:  []
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst:             5.5
    Catalyst::Plugin::Authentication:  0
    LWP::Simple:          0
    Test::MockObject:     1.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
